//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorerTabUtility.Strings {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Res() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExplorerTabUtility.Strings.Strings", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // MainWindow
        public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture);
        public static string NavShortcuts => ResourceManager.GetString("NavShortcuts", resourceCulture);
        public static string NavPreferences => ResourceManager.GetString("NavPreferences", resourceCulture);
        public static string NavAbout => ResourceManager.GetString("NavAbout", resourceCulture);
        public static string BtnNew => ResourceManager.GetString("BtnNew", resourceCulture);
        public static string BtnImport => ResourceManager.GetString("BtnImport", resourceCulture);
        public static string BtnExport => ResourceManager.GetString("BtnExport", resourceCulture);
        public static string BtnSave => ResourceManager.GetString("BtnSave", resourceCulture);
        public static string CbAutoSave => ResourceManager.GetString("CbAutoSave", resourceCulture);
        public static string GrpAppSettings => ResourceManager.GetString("GrpAppSettings", resourceCulture);
        public static string CbAutoUpdate => ResourceManager.GetString("CbAutoUpdate", resourceCulture);
        public static string CbThemeIssue => ResourceManager.GetString("CbThemeIssue", resourceCulture);
        public static string CbSaveClosedHistory => ResourceManager.GetString("CbSaveClosedHistory", resourceCulture);
        public static string CbRestorePrevious => ResourceManager.GetString("CbRestorePrevious", resourceCulture);
        public static string CbHideTrayIcon => ResourceManager.GetString("CbHideTrayIcon", resourceCulture);
        public static string StatusWindowHook => ResourceManager.GetString("StatusWindowHook", resourceCulture);
        public static string StatusReuseTabs => ResourceManager.GetString("StatusReuseTabs", resourceCulture);
        public static string StatusKeyboardHook => ResourceManager.GetString("StatusKeyboardHook", resourceCulture);
        public static string StatusMouseHook => ResourceManager.GetString("StatusMouseHook", resourceCulture);

        // ToolTips MainWindow
        public static string TipOpenAppMenu => ResourceManager.GetString("TipOpenAppMenu", resourceCulture);
        public static string TipConfigureShortcuts => ResourceManager.GetString("TipConfigureShortcuts", resourceCulture);
        public static string TipConfigureSettings => ResourceManager.GetString("TipConfigureSettings", resourceCulture);
        public static string TipAboutApp => ResourceManager.GetString("TipAboutApp", resourceCulture);
        public static string TipCreateProfile => ResourceManager.GetString("TipCreateProfile", resourceCulture);
        public static string TipImportProfiles => ResourceManager.GetString("TipImportProfiles", resourceCulture);
        public static string TipExportProfiles => ResourceManager.GetString("TipExportProfiles", resourceCulture);
        public static string TipSaveProfiles => ResourceManager.GetString("TipSaveProfiles", resourceCulture);
        public static string TipAutoSave => ResourceManager.GetString("TipAutoSave", resourceCulture);
        public static string TipAutoUpdate => ResourceManager.GetString("TipAutoUpdate", resourceCulture);
        public static string TipThemeIssue => ResourceManager.GetString("TipThemeIssue", resourceCulture);
        public static string TipSaveClosedHistory => ResourceManager.GetString("TipSaveClosedHistory", resourceCulture);
        public static string TipRestorePrevious => ResourceManager.GetString("TipRestorePrevious", resourceCulture);
        public static string TipHideTrayIcon => ResourceManager.GetString("TipHideTrayIcon", resourceCulture);

        // SystemTrayIcon
        public static string MenuKeyboardHook => ResourceManager.GetString("MenuKeyboardHook", resourceCulture);
        public static string MenuMouseHook => ResourceManager.GetString("MenuMouseHook", resourceCulture);
        public static string MenuWindowHook => ResourceManager.GetString("MenuWindowHook", resourceCulture);
        public static string MenuReuseTabs => ResourceManager.GetString("MenuReuseTabs", resourceCulture);
        public static string MenuAddToStartup => ResourceManager.GetString("MenuAddToStartup", resourceCulture);
        public static string MenuCheckUpdates => ResourceManager.GetString("MenuCheckUpdates", resourceCulture);
        public static string MenuSettings => ResourceManager.GetString("MenuSettings", resourceCulture);
        public static string MenuExit => ResourceManager.GetString("MenuExit", resourceCulture);

        // ToolTips SystemTrayIcon
        public static string TipEnableKeyboard => ResourceManager.GetString("TipEnableKeyboard", resourceCulture);
        public static string TipEnableMouse => ResourceManager.GetString("TipEnableMouse", resourceCulture);
        public static string TipToggleWindowHook => ResourceManager.GetString("TipToggleWindowHook", resourceCulture);
        public static string TipToggleReuseTabs => ResourceManager.GetString("TipToggleReuseTabs", resourceCulture);
        public static string TipToggleStartup => ResourceManager.GetString("TipToggleStartup", resourceCulture);
        public static string TipCheckUpdates => ResourceManager.GetString("TipCheckUpdates", resourceCulture);
        public static string TipOpenSettings => ResourceManager.GetString("TipOpenSettings", resourceCulture);
        public static string TipExitApp => ResourceManager.GetString("TipExitApp", resourceCulture);

        // HotKeyProfileControl
        public static string ProfileHandled => ResourceManager.GetString("ProfileHandled", resourceCulture);
        public static string ProfileTab => ResourceManager.GetString("ProfileTab", resourceCulture);
        public static string ProfileDelay => ResourceManager.GetString("ProfileDelay", resourceCulture);
        public static string TipEnableProfile => ResourceManager.GetString("TipEnableProfile", resourceCulture);
        public static string TipProfileName => ResourceManager.GetString("TipProfileName", resourceCulture);
        public static string TipProfileHotkeys => ResourceManager.GetString("TipProfileHotkeys", resourceCulture);
        public static string TipProfileScope => ResourceManager.GetString("TipProfileScope", resourceCulture);
        public static string TipProfileAction => ResourceManager.GetString("TipProfileAction", resourceCulture);
        public static string TipShowMore => ResourceManager.GetString("TipShowMore", resourceCulture);
        public static string TipDeleteProfile => ResourceManager.GetString("TipDeleteProfile", resourceCulture);
        public static string TipProfilePath => ResourceManager.GetString("TipProfilePath", resourceCulture);
        public static string TipProfileDelay => ResourceManager.GetString("TipProfileDelay", resourceCulture);
        public static string TipProfileHandled => ResourceManager.GetString("TipProfileHandled", resourceCulture);
        public static string TipProfileAsTab => ResourceManager.GetString("TipProfileAsTab", resourceCulture);

        // TabSearchPopup
        public static string TipClearHistory => ResourceManager.GetString("TipClearHistory", resourceCulture);
        public static string ConfirmClearHistory => ResourceManager.GetString("ConfirmClearHistory", resourceCulture);
        public static string ConfirmClearHistoryTitle => ResourceManager.GetString("ConfirmClearHistoryTitle", resourceCulture);

        // AboutView
        public static string AboutSubtitle => ResourceManager.GetString("AboutSubtitle", resourceCulture);
        public static string AboutStarGitHub => ResourceManager.GetString("AboutStarGitHub", resourceCulture);
        public static string AboutSupportProject => ResourceManager.GetString("AboutSupportProject", resourceCulture);
        public static string AboutSupportDesc => ResourceManager.GetString("AboutSupportDesc", resourceCulture);
        public static string AboutDeveloper => ResourceManager.GetString("AboutDeveloper", resourceCulture);
        public static string AboutCurrentSupporters => ResourceManager.GetString("AboutCurrentSupporters", resourceCulture);
        public static string AboutSupportersDesc => ResourceManager.GetString("AboutSupportersDesc", resourceCulture);
        public static string AboutBeFirst => ResourceManager.GetString("AboutBeFirst", resourceCulture);
        public static string AboutKeepAlive => ResourceManager.GetString("AboutKeepAlive", resourceCulture);

        // CustomMessageBox
        public static string BtnOK => ResourceManager.GetString("BtnOK", resourceCulture);
        public static string BtnCancel => ResourceManager.GetString("BtnCancel", resourceCulture);
        public static string BtnYes => ResourceManager.GetString("BtnYes", resourceCulture);
        public static string BtnNo => ResourceManager.GetString("BtnNo", resourceCulture);

        // Dialog Messages
        public static string MsgAnotherInstance => ResourceManager.GetString("MsgAnotherInstance", resourceCulture);
        public static string MsgRestoreWindows => ResourceManager.GetString("MsgRestoreWindows", resourceCulture);
        public static string MsgToggleVisibility => ResourceManager.GetString("MsgToggleVisibility", resourceCulture);
        public static string MsgNoToggleVisibility => ResourceManager.GetString("MsgNoToggleVisibility", resourceCulture);

        // Constants
        public static string NotifyIconText => ResourceManager.GetString("NotifyIconText", resourceCulture);

        // Language Settings
        public static string GrpLanguage => ResourceManager.GetString("GrpLanguage", resourceCulture);
        public static string LblLanguage => ResourceManager.GetString("LblLanguage", resourceCulture);
        public static string TipLanguage => ResourceManager.GetString("TipLanguage", resourceCulture);
        public static string TipLanguageRestart => ResourceManager.GetString("TipLanguageRestart", resourceCulture);

        // HotKeyAction Descriptions
        public static string Action_Open => ResourceManager.GetString("Action_Open", resourceCulture);
        public static string Action_Duplicate => ResourceManager.GetString("Action_Duplicate", resourceCulture);
        public static string Action_ReopenClosed => ResourceManager.GetString("Action_ReopenClosed", resourceCulture);
        public static string Action_TabSearch => ResourceManager.GetString("Action_TabSearch", resourceCulture);
        public static string Action_NavigateBack => ResourceManager.GetString("Action_NavigateBack", resourceCulture);
        public static string Action_NavigateUp => ResourceManager.GetString("Action_NavigateUp", resourceCulture);
        public static string Action_NavigateForward => ResourceManager.GetString("Action_NavigateForward", resourceCulture);
        public static string Action_SetTargetWindow => ResourceManager.GetString("Action_SetTargetWindow", resourceCulture);
        public static string Action_ToggleWinHook => ResourceManager.GetString("Action_ToggleWinHook", resourceCulture);
        public static string Action_ToggleReuseTabs => ResourceManager.GetString("Action_ToggleReuseTabs", resourceCulture);
        public static string Action_ToggleVisibility => ResourceManager.GetString("Action_ToggleVisibility", resourceCulture);
        public static string Action_DetachTab => ResourceManager.GetString("Action_DetachTab", resourceCulture);
        public static string Action_SnapRight => ResourceManager.GetString("Action_SnapRight", resourceCulture);
        public static string Action_SnapLeft => ResourceManager.GetString("Action_SnapLeft", resourceCulture);
        public static string Action_SnapUp => ResourceManager.GetString("Action_SnapUp", resourceCulture);
        public static string Action_SnapDown => ResourceManager.GetString("Action_SnapDown", resourceCulture);

        // Scope
        public static string ScopeGlobal => ResourceManager.GetString("ScopeGlobal", resourceCulture);
        public static string ScopeFileExplorer => ResourceManager.GetString("ScopeFileExplorer", resourceCulture);

        // Built-in Double-Click Empty Space
        public static string GrpMouseFeatures => ResourceManager.GetString("GrpMouseFeatures", resourceCulture);
        public static string CbDoubleClickEmptySpace => ResourceManager.GetString("CbDoubleClickEmptySpace", resourceCulture);
        public static string TipDoubleClickEmptySpace => ResourceManager.GetString("TipDoubleClickEmptySpace", resourceCulture);
    }
}
