//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorerTabUtility.Strings {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExplorerTabUtility.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // MainWindow
        internal static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture);
        internal static string NavShortcuts => ResourceManager.GetString("NavShortcuts", resourceCulture);
        internal static string NavPreferences => ResourceManager.GetString("NavPreferences", resourceCulture);
        internal static string NavAbout => ResourceManager.GetString("NavAbout", resourceCulture);
        internal static string BtnNew => ResourceManager.GetString("BtnNew", resourceCulture);
        internal static string BtnImport => ResourceManager.GetString("BtnImport", resourceCulture);
        internal static string BtnExport => ResourceManager.GetString("BtnExport", resourceCulture);
        internal static string BtnSave => ResourceManager.GetString("BtnSave", resourceCulture);
        internal static string CbAutoSave => ResourceManager.GetString("CbAutoSave", resourceCulture);
        internal static string GrpAppSettings => ResourceManager.GetString("GrpAppSettings", resourceCulture);
        internal static string CbAutoUpdate => ResourceManager.GetString("CbAutoUpdate", resourceCulture);
        internal static string CbThemeIssue => ResourceManager.GetString("CbThemeIssue", resourceCulture);
        internal static string CbSaveClosedHistory => ResourceManager.GetString("CbSaveClosedHistory", resourceCulture);
        internal static string CbRestorePrevious => ResourceManager.GetString("CbRestorePrevious", resourceCulture);
        internal static string CbHideTrayIcon => ResourceManager.GetString("CbHideTrayIcon", resourceCulture);
        internal static string StatusWindowHook => ResourceManager.GetString("StatusWindowHook", resourceCulture);
        internal static string StatusReuseTabs => ResourceManager.GetString("StatusReuseTabs", resourceCulture);
        internal static string StatusKeyboardHook => ResourceManager.GetString("StatusKeyboardHook", resourceCulture);
        internal static string StatusMouseHook => ResourceManager.GetString("StatusMouseHook", resourceCulture);

        // ToolTips MainWindow
        internal static string TipOpenAppMenu => ResourceManager.GetString("TipOpenAppMenu", resourceCulture);
        internal static string TipConfigureShortcuts => ResourceManager.GetString("TipConfigureShortcuts", resourceCulture);
        internal static string TipConfigureSettings => ResourceManager.GetString("TipConfigureSettings", resourceCulture);
        internal static string TipAboutApp => ResourceManager.GetString("TipAboutApp", resourceCulture);
        internal static string TipCreateProfile => ResourceManager.GetString("TipCreateProfile", resourceCulture);
        internal static string TipImportProfiles => ResourceManager.GetString("TipImportProfiles", resourceCulture);
        internal static string TipExportProfiles => ResourceManager.GetString("TipExportProfiles", resourceCulture);
        internal static string TipSaveProfiles => ResourceManager.GetString("TipSaveProfiles", resourceCulture);
        internal static string TipAutoSave => ResourceManager.GetString("TipAutoSave", resourceCulture);
        internal static string TipAutoUpdate => ResourceManager.GetString("TipAutoUpdate", resourceCulture);
        internal static string TipThemeIssue => ResourceManager.GetString("TipThemeIssue", resourceCulture);
        internal static string TipSaveClosedHistory => ResourceManager.GetString("TipSaveClosedHistory", resourceCulture);
        internal static string TipRestorePrevious => ResourceManager.GetString("TipRestorePrevious", resourceCulture);
        internal static string TipHideTrayIcon => ResourceManager.GetString("TipHideTrayIcon", resourceCulture);

        // SystemTrayIcon
        internal static string MenuKeyboardHook => ResourceManager.GetString("MenuKeyboardHook", resourceCulture);
        internal static string MenuMouseHook => ResourceManager.GetString("MenuMouseHook", resourceCulture);
        internal static string MenuWindowHook => ResourceManager.GetString("MenuWindowHook", resourceCulture);
        internal static string MenuReuseTabs => ResourceManager.GetString("MenuReuseTabs", resourceCulture);
        internal static string MenuAddToStartup => ResourceManager.GetString("MenuAddToStartup", resourceCulture);
        internal static string MenuCheckUpdates => ResourceManager.GetString("MenuCheckUpdates", resourceCulture);
        internal static string MenuSettings => ResourceManager.GetString("MenuSettings", resourceCulture);
        internal static string MenuExit => ResourceManager.GetString("MenuExit", resourceCulture);

        // ToolTips SystemTrayIcon
        internal static string TipEnableKeyboard => ResourceManager.GetString("TipEnableKeyboard", resourceCulture);
        internal static string TipEnableMouse => ResourceManager.GetString("TipEnableMouse", resourceCulture);
        internal static string TipToggleWindowHook => ResourceManager.GetString("TipToggleWindowHook", resourceCulture);
        internal static string TipToggleReuseTabs => ResourceManager.GetString("TipToggleReuseTabs", resourceCulture);
        internal static string TipToggleStartup => ResourceManager.GetString("TipToggleStartup", resourceCulture);
        internal static string TipCheckUpdates => ResourceManager.GetString("TipCheckUpdates", resourceCulture);
        internal static string TipOpenSettings => ResourceManager.GetString("TipOpenSettings", resourceCulture);
        internal static string TipExitApp => ResourceManager.GetString("TipExitApp", resourceCulture);

        // HotKeyProfileControl
        internal static string ProfileHandled => ResourceManager.GetString("ProfileHandled", resourceCulture);
        internal static string ProfileTab => ResourceManager.GetString("ProfileTab", resourceCulture);
        internal static string ProfileDelay => ResourceManager.GetString("ProfileDelay", resourceCulture);
        internal static string TipEnableProfile => ResourceManager.GetString("TipEnableProfile", resourceCulture);
        internal static string TipProfileName => ResourceManager.GetString("TipProfileName", resourceCulture);
        internal static string TipProfileHotkeys => ResourceManager.GetString("TipProfileHotkeys", resourceCulture);
        internal static string TipProfileScope => ResourceManager.GetString("TipProfileScope", resourceCulture);
        internal static string TipProfileAction => ResourceManager.GetString("TipProfileAction", resourceCulture);
        internal static string TipShowMore => ResourceManager.GetString("TipShowMore", resourceCulture);
        internal static string TipDeleteProfile => ResourceManager.GetString("TipDeleteProfile", resourceCulture);
        internal static string TipProfilePath => ResourceManager.GetString("TipProfilePath", resourceCulture);
        internal static string TipProfileDelay => ResourceManager.GetString("TipProfileDelay", resourceCulture);
        internal static string TipProfileHandled => ResourceManager.GetString("TipProfileHandled", resourceCulture);
        internal static string TipProfileAsTab => ResourceManager.GetString("TipProfileAsTab", resourceCulture);

        // TabSearchPopup
        internal static string TipClearHistory => ResourceManager.GetString("TipClearHistory", resourceCulture);
        internal static string ConfirmClearHistory => ResourceManager.GetString("ConfirmClearHistory", resourceCulture);
        internal static string ConfirmClearHistoryTitle => ResourceManager.GetString("ConfirmClearHistoryTitle", resourceCulture);

        // AboutView
        internal static string AboutSubtitle => ResourceManager.GetString("AboutSubtitle", resourceCulture);
        internal static string AboutStarGitHub => ResourceManager.GetString("AboutStarGitHub", resourceCulture);
        internal static string AboutSupportProject => ResourceManager.GetString("AboutSupportProject", resourceCulture);
        internal static string AboutSupportDesc => ResourceManager.GetString("AboutSupportDesc", resourceCulture);
        internal static string AboutDeveloper => ResourceManager.GetString("AboutDeveloper", resourceCulture);
        internal static string AboutCurrentSupporters => ResourceManager.GetString("AboutCurrentSupporters", resourceCulture);
        internal static string AboutSupportersDesc => ResourceManager.GetString("AboutSupportersDesc", resourceCulture);
        internal static string AboutBeFirst => ResourceManager.GetString("AboutBeFirst", resourceCulture);
        internal static string AboutKeepAlive => ResourceManager.GetString("AboutKeepAlive", resourceCulture);

        // CustomMessageBox
        internal static string BtnOK => ResourceManager.GetString("BtnOK", resourceCulture);
        internal static string BtnCancel => ResourceManager.GetString("BtnCancel", resourceCulture);
        internal static string BtnYes => ResourceManager.GetString("BtnYes", resourceCulture);
        internal static string BtnNo => ResourceManager.GetString("BtnNo", resourceCulture);

        // Dialog Messages
        internal static string MsgAnotherInstance => ResourceManager.GetString("MsgAnotherInstance", resourceCulture);
        internal static string MsgRestoreWindows => ResourceManager.GetString("MsgRestoreWindows", resourceCulture);
        internal static string MsgToggleVisibility => ResourceManager.GetString("MsgToggleVisibility", resourceCulture);
        internal static string MsgNoToggleVisibility => ResourceManager.GetString("MsgNoToggleVisibility", resourceCulture);

        // Constants
        internal static string NotifyIconText => ResourceManager.GetString("NotifyIconText", resourceCulture);

        // HotKeyAction Descriptions
        internal static string Action_Open => ResourceManager.GetString("Action_Open", resourceCulture);
        internal static string Action_Duplicate => ResourceManager.GetString("Action_Duplicate", resourceCulture);
        internal static string Action_ReopenClosed => ResourceManager.GetString("Action_ReopenClosed", resourceCulture);
        internal static string Action_TabSearch => ResourceManager.GetString("Action_TabSearch", resourceCulture);
        internal static string Action_NavigateBack => ResourceManager.GetString("Action_NavigateBack", resourceCulture);
        internal static string Action_NavigateUp => ResourceManager.GetString("Action_NavigateUp", resourceCulture);
        internal static string Action_NavigateForward => ResourceManager.GetString("Action_NavigateForward", resourceCulture);
        internal static string Action_SetTargetWindow => ResourceManager.GetString("Action_SetTargetWindow", resourceCulture);
        internal static string Action_ToggleWinHook => ResourceManager.GetString("Action_ToggleWinHook", resourceCulture);
        internal static string Action_ToggleReuseTabs => ResourceManager.GetString("Action_ToggleReuseTabs", resourceCulture);
        internal static string Action_ToggleVisibility => ResourceManager.GetString("Action_ToggleVisibility", resourceCulture);
        internal static string Action_DetachTab => ResourceManager.GetString("Action_DetachTab", resourceCulture);
        internal static string Action_SnapRight => ResourceManager.GetString("Action_SnapRight", resourceCulture);
        internal static string Action_SnapLeft => ResourceManager.GetString("Action_SnapLeft", resourceCulture);
        internal static string Action_SnapUp => ResourceManager.GetString("Action_SnapUp", resourceCulture);
        internal static string Action_SnapDown => ResourceManager.GetString("Action_SnapDown", resourceCulture);
    }
}
